import java.awt.event.ActionListener;

/**The given class, GrassGUI is the GUI for choosing grass type creatures
 * <p>
 * It consists attributes that handles for the actions in each GUI
 * <ul>
 * </ul>
 * @author De los Reyes, Carl Justin B.
 * </p>
 * */
public class GrassGUI extends javax.swing.JFrame {

    /**
     * Creates new form GrassGUI
     */
    public GrassGUI() {
        initComponents();
        setSize(800, 535);
        setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */

    private void initComponents() {

        leftpanel = new javax.swing.JPanel();
        GRASS = new javax.swing.JLabel();
        Brownisaurdetails = new javax.swing.JPanel();
        nameb = new javax.swing.JLabel();
        familyd = new javax.swing.JLabel();
        grasstypeb = new javax.swing.JLabel();
        level1b = new javax.swing.JLabel();
        frubatdetails = new javax.swing.JPanel();
        namef = new javax.swing.JLabel();
        familye = new javax.swing.JLabel();
        grasstypef = new javax.swing.JLabel();
        levelf = new javax.swing.JLabel();
        maltsdetails = new javax.swing.JPanel();
        namem = new javax.swing.JLabel();
        familyf = new javax.swing.JLabel();
        grasstypem = new javax.swing.JLabel();
        levelm = new javax.swing.JLabel();
        maltsimg = new javax.swing.JLabel();
        frubatimg = new javax.swing.JLabel();
        bulbasaurimg = new javax.swing.JLabel();
        grasslogo2 = new javax.swing.JLabel();
        grasslogo1 = new javax.swing.JLabel();
        Background = new javax.swing.JPanel();
        Grasstype = new javax.swing.JLabel();
        SelectStarter1 = new javax.swing.JLabel();
        Cloud5 = new javax.swing.JLabel();
        Cloud4 = new javax.swing.JLabel();
        Cloud3 = new javax.swing.JLabel();
        Cloud2 = new javax.swing.JLabel();
        Cloud1 = new javax.swing.JLabel();
        backgrass = new javax.swing.JButton();
        brownidaur = new javax.swing.JButton();
        frubat = new javax.swing.JButton();
        malts = new javax.swing.JButton();
        Grass1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        leftpanel.setBackground(new java.awt.Color(246, 246, 199));
        leftpanel.setLayout(null);

        GRASS.setFont(new java.awt.Font("Franklin Gothic Heavy", 0, 36)); // NOI18N
        GRASS.setForeground(new java.awt.Color(0, 102, 51));
        GRASS.setText("GRASS TYPE");
        GRASS.setName(""); // NOI18N
        GRASS.setPreferredSize(new java.awt.Dimension(130, 16));
        leftpanel.add(GRASS);
        GRASS.setBounds(90, 0, 390, 60);

        Brownisaurdetails.setBackground(new java.awt.Color(214, 232, 232));

        nameb.setFont(new java.awt.Font("SimSun", 1, 12)); // NOI18N
        nameb.setText("Name: Brownisaur");

        familyd.setFont(new java.awt.Font("SimSun", 1, 12)); // NOI18N
        familyd.setText("Family: D");

        grasstypeb.setFont(new java.awt.Font("SimSun", 1, 12)); // NOI18N
        grasstypeb.setText("Type: Grass ");

        level1b.setFont(new java.awt.Font("SimSun", 1, 12)); // NOI18N
        level1b.setText("Level: 1");

        javax.swing.GroupLayout BrownisaurdetailsLayout = new javax.swing.GroupLayout(Brownisaurdetails);
        Brownisaurdetails.setLayout(BrownisaurdetailsLayout);
        BrownisaurdetailsLayout.setHorizontalGroup(
                BrownisaurdetailsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(BrownisaurdetailsLayout.createSequentialGroup()
                                .addGap(22, 22, 22)
                                .addGroup(BrownisaurdetailsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(level1b)
                                        .addComponent(familyd)
                                        .addComponent(nameb)
                                        .addComponent(grasstypeb))
                                .addContainerGap(46, Short.MAX_VALUE))
        );
        BrownisaurdetailsLayout.setVerticalGroup(
                BrownisaurdetailsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(BrownisaurdetailsLayout.createSequentialGroup()
                                .addGap(12, 12, 12)
                                .addComponent(nameb)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(familyd)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(grasstypeb)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(level1b)
                                .addContainerGap(10, Short.MAX_VALUE))
        );

        leftpanel.add(Brownisaurdetails);
        Brownisaurdetails.setBounds(200, 80, 170, 100);

        frubatdetails.setBackground(new java.awt.Color(214, 232, 232));

        namef.setFont(new java.awt.Font("SimSun", 1, 12)); // NOI18N
        namef.setText("Name: Frubat");

        familye.setFont(new java.awt.Font("SimSun", 1, 12)); // NOI18N
        familye.setText("Family: E");

        grasstypef.setFont(new java.awt.Font("SimSun", 1, 12)); // NOI18N
        grasstypef.setText("Type: Grass");

        levelf.setFont(new java.awt.Font("SimSun", 1, 12)); // NOI18N
        levelf.setText("Level: 1");

        javax.swing.GroupLayout frubatdetailsLayout = new javax.swing.GroupLayout(frubatdetails);
        frubatdetails.setLayout(frubatdetailsLayout);
        frubatdetailsLayout.setHorizontalGroup(
                frubatdetailsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(frubatdetailsLayout.createSequentialGroup()
                                .addGap(22, 22, 22)
                                .addGroup(frubatdetailsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(levelf)
                                        .addComponent(familye)
                                        .addComponent(namef)
                                        .addComponent(grasstypef))
                                .addContainerGap(72, Short.MAX_VALUE))
        );
        frubatdetailsLayout.setVerticalGroup(
                frubatdetailsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(frubatdetailsLayout.createSequentialGroup()
                                .addGap(10, 10, 10)
                                .addComponent(namef)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(familye)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(grasstypef)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(levelf)
                                .addGap(12, 12, 12))
        );

        leftpanel.add(frubatdetails);
        frubatdetails.setBounds(200, 230, 170, 100);

        maltsdetails.setBackground(new java.awt.Color(214, 232, 232));

        namem.setFont(new java.awt.Font("SimSun", 1, 12)); // NOI18N
        namem.setText("Name: Malts");

        familyf.setFont(new java.awt.Font("SimSun", 1, 12)); // NOI18N
        familyf.setText("Family: F");

        grasstypem.setFont(new java.awt.Font("SimSun", 1, 12)); // NOI18N
        grasstypem.setText("Type: Grass");

        levelm.setFont(new java.awt.Font("SimSun", 1, 12)); // NOI18N
        levelm.setText("Level: 1");

        javax.swing.GroupLayout maltsdetailsLayout = new javax.swing.GroupLayout(maltsdetails);
        maltsdetails.setLayout(maltsdetailsLayout);
        maltsdetailsLayout.setHorizontalGroup(
                maltsdetailsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(maltsdetailsLayout.createSequentialGroup()
                                .addGap(21, 21, 21)
                                .addGroup(maltsdetailsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(levelm)
                                        .addComponent(grasstypem)
                                        .addComponent(familyf)
                                        .addComponent(namem))
                                .addContainerGap(79, Short.MAX_VALUE))
        );
        maltsdetailsLayout.setVerticalGroup(
                maltsdetailsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(maltsdetailsLayout.createSequentialGroup()
                                .addGap(10, 10, 10)
                                .addComponent(namem)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(familyf)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(grasstypem, javax.swing.GroupLayout.PREFERRED_SIZE, 15, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(levelm)
                                .addContainerGap(12, Short.MAX_VALUE))
        );

        leftpanel.add(maltsdetails);
        maltsdetails.setBounds(200, 370, 170, 100);

        maltsimg.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/malts.png"))); // NOI18N
        maltsimg.setText("jLabel3");
        leftpanel.add(maltsimg);
        maltsimg.setBounds(-20, 300, 200, 230);

        frubatimg.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/frubat.png"))); // NOI18N
        frubatimg.setText("jLabel2");
        leftpanel.add(frubatimg);
        frubatimg.setBounds(-20, 150, 300, 240);

        bulbasaurimg.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/bulbasaur.png"))); // NOI18N
        bulbasaurimg.setText("jLabel1");
        leftpanel.add(bulbasaurimg);
        bulbasaurimg.setBounds(-20, 10, 210, 230);

        grasslogo2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/geass logo (2).png"))); // NOI18N
        grasslogo2.setText("jLabel2");
        leftpanel.add(grasslogo2);
        grasslogo2.setBounds(-130, 340, 280, 200);

        grasslogo1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/geass logo (2).png"))); // NOI18N
        grasslogo1.setText("jLabel2");
        leftpanel.add(grasslogo1);
        grasslogo1.setBounds(160, -60, 280, 200);

        Background.setBackground(new java.awt.Color(214, 232, 232));
        Background.setLayout(null);

        Grasstype.setFont(new java.awt.Font("Lucida Sans", 0, 14)); // NOI18N
        Grasstype.setText("GRASS Type");
        Background.add(Grasstype);
        Grasstype.setBounds(550, 130, 230, 22);

        SelectStarter1.setFont(new java.awt.Font("Lucida Sans", 0, 18)); // NOI18N
        SelectStarter1.setText("Select Starter Creature");
        Background.add(SelectStarter1);
        SelectStarter1.setBounds(500, 80, 230, 22);

        Cloud5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/Orange and Green Modern Icons Food Logo (5).png"))); // NOI18N
        Cloud5.setText("jLabel1");
        Background.add(Cloud5);
        Cloud5.setBounds(690, -110, 160, 180);

        Cloud4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/Orange and Green Modern Icons Food Logo (5).png"))); // NOI18N
        Cloud4.setText("jLabel1");
        Background.add(Cloud4);
        Cloud4.setBounds(370, -140, 160, 260);

        Cloud3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/Orange and Green Modern Icons Food Logo (5).png"))); // NOI18N
        Cloud3.setText("jLabel1");
        Background.add(Cloud3);
        Cloud3.setBounds(600, -30, 140, 160);

        Cloud2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/Orange and Green Modern Icons Food Logo (5).png"))); // NOI18N
        Cloud2.setText("jLabel1");
        Background.add(Cloud2);
        Cloud2.setBounds(450, -100, 140, 160);

        Cloud1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/Orange and Green Modern Icons Food Logo (5).png"))); // NOI18N
        Cloud1.setText("jLabel1");
        Background.add(Cloud1);
        Cloud1.setBounds(660, -50, 140, 160);

        backgrass.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        backgrass.setForeground(new java.awt.Color(102, 102, 102));
        backgrass.setText("Back");
        backgrass.setBorderPainted(false);
        backgrass.setFocusPainted(false);

        Background.add(backgrass);
        backgrass.setBounds(530, 350, 130, 40);

        brownidaur.setBackground(new java.awt.Color(0, 102, 102));
        brownidaur.setForeground(new java.awt.Color(255, 255, 255));
        brownidaur.setText("Brownisaur");
        brownidaur.setBorderPainted(false);
        brownidaur.setFocusPainted(false);

        Background.add(brownidaur);
        brownidaur.setBounds(530, 170, 130, 40);

        frubat.setBackground(new java.awt.Color(0, 102, 102));
        frubat.setForeground(new java.awt.Color(255, 255, 255));
        frubat.setText("Frubat");
        frubat.setBorderPainted(false);
        frubat.setFocusPainted(false);

        Background.add(frubat);
        frubat.setBounds(530, 220, 130, 40);

        malts.setBackground(new java.awt.Color(0, 102, 102));
        malts.setForeground(new java.awt.Color(255, 255, 255));
        malts.setText("Malts");
        malts.setBorderPainted(false);
        malts.setFocusPainted(false);

        Background.add(malts);
        malts.setBounds(530, 270, 130, 40);

        Grass1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/Orange and Green Modern Icons Food Logo (10).png"))); // NOI18N
        Background.add(Grass1);
        Grass1.setBounds(400, 290, 797, 230);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
                layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(layout.createSequentialGroup()
                                .addComponent(leftpanel, javax.swing.GroupLayout.PREFERRED_SIZE, 413, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(0, 391, Short.MAX_VALUE))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(Background, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 804, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
                layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(leftpanel, javax.swing.GroupLayout.DEFAULT_SIZE, 510, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(Background, javax.swing.GroupLayout.DEFAULT_SIZE, 510, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>


    public void backgrassActionListener(ActionListener listener) {
        backgrass.addActionListener(listener);
    }

    public void brownisaurActionListener(ActionListener listener) {
        brownidaur.addActionListener(listener);
    }

    public void frubatActionListener(ActionListener listener) {
        frubat.addActionListener(listener);
    }


    public void maltsActionListener(ActionListener listener) {
        malts.addActionListener(listener);
    }

    // Variables declaration - do not modify
    private javax.swing.JPanel Background;
    private javax.swing.JPanel Brownisaurdetails;
    private javax.swing.JLabel Cloud1;
    private javax.swing.JLabel Cloud2;
    private javax.swing.JLabel Cloud3;
    private javax.swing.JLabel Cloud4;
    private javax.swing.JLabel Cloud5;
    private javax.swing.JLabel GRASS;
    private javax.swing.JLabel Grass1;
    private javax.swing.JLabel Grasstype;
    private javax.swing.JLabel SelectStarter1;
    private javax.swing.JButton backgrass;
    private javax.swing.JButton brownidaur;
    private javax.swing.JLabel bulbasaurimg;
    private javax.swing.JLabel familyd;
    private javax.swing.JLabel familye;
    private javax.swing.JLabel familyf;
    private javax.swing.JButton frubat;
    private javax.swing.JPanel frubatdetails;
    private javax.swing.JLabel frubatimg;
    private javax.swing.JLabel grasslogo1;
    private javax.swing.JLabel grasslogo2;
    private javax.swing.JLabel grasstypeb;
    private javax.swing.JLabel grasstypef;
    private javax.swing.JLabel grasstypem;
    private javax.swing.JPanel leftpanel;
    private javax.swing.JLabel level1b;
    private javax.swing.JLabel levelf;
    private javax.swing.JLabel levelm;
    private javax.swing.JButton malts;
    private javax.swing.JPanel maltsdetails;
    private javax.swing.JLabel maltsimg;
    private javax.swing.JLabel nameb;
    private javax.swing.JLabel namef;
    private javax.swing.JLabel namem;
    // End of variables declaration
}
